import type { Metadata } from "next";
import Link from "next/link";

import AnchorRedirect from "@/components/AnchorRedirect";
import { intro } from "@/components/DocsProse";
import { Pager } from "@/components/DocViews";
import UpdatedPill from "@/components/UpdatedPill";
import { updatedAll, version } from "@/lib/content";
import { liveGroups, movedAnchors, pageAt, pages } from "@/lib/docs";

// The docs home: what Alloy is, and a map of every group of pages. It
// also sends an old `/docs/#<anchor>` link on to its page.

export const metadata: Metadata = {
  title: "Docs",
  description:
    "The Alloy docs: install, the language beside its emitted Luau, the toolchain, the configuration, and a reference for every keyword, std type, error kind, and lint.",
  alternates: { canonical: "/docs/" },
  openGraph: {
    title: "The Alloy docs",
    description:
      "Every Alloy construct with its emitted Luau beside it, the toolchain and its configuration, and a reference for every keyword, std type, and lint.",
    url: "/docs/",
  },
};

export default function Docs() {
  return (
    <article>
      <AnchorRedirect moved={movedAnchors()} />
      <header className="mb-10">
        <div className="eyebrow">The Alloy docs</div>
        <h1 className="display mt-2 mb-3 text-[36px] font-extrabold leading-[1.05] md:text-[48px]">
          Everything the compiler knows.
        </h1>
        <p className="prose m-0 max-w-[60ch] text-[17px] text-ink-2">
          Start with the install, then read the language pages in order. Look up one keyword, std type, error, or lint in
          the reference. The reference pages carry the same text the editor shows on hover, generated from the
          compiler&apos;s own table.
        </p>
        <div className="mt-5">
          <UpdatedPill date={updatedAll} label="Last updated" size="md" />
        </div>
      </header>

      <section className="mb-12">
        <h2 id="intro" className="display mb-4 text-[24px] font-bold">
          Introduction
        </h2>
        {intro}
      </section>

      {liveGroups.map((g) => {
        const items = pages.filter((p) => p.group === g.slug && p.view.kind !== "group" && p.view.kind !== "home" && !p.parent);

        return (
          <section key={g.slug} className="mb-10">
            <h2 id={g.slug} className="display mb-1 text-[24px] font-bold">
              <Link href={`/docs/${g.slug}/`} className="text-ink no-underline hover:text-accent-ink">
                {g.title}
              </Link>
            </h2>
            <p className="m-0 mb-4 text-[15px] text-ink-2">{g.blurb}</p>
            <ul className="home-links">
              {items.map((p) => (
                <li key={p.path}>
                  <Link href={p.path}>{p.title}</Link>
                </li>
              ))}
            </ul>
          </section>
        );
      })}

      <Pager page={pageAt("/docs/")!} />

      <footer className="mt-10 border-t border-line pt-6 text-[13px] text-muted">
        Alloy {version}. The reference text is generated by <code className="font-mono">alloy doc --json</code>.
      </footer>
    </article>
  );
}
